name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # <-- Release बनाने का परमिशन
    steps:
      - uses: actions/checkout@v3
      - run: gh release create 1.0 --generate-notes -F release.md oci-ods-aqua.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
